IDENTITY_BASE_URL = r"/identity"
COMPUTE_BASE_URL = r"/compute"
BLOCK_STORAGE_BASE_URL = r"/block_storage"
IMAGE_SERVICE_BASE_URL = r"/image_service"
NETWORKING_BASE_URL = r"/networking"
OBJECT_STORAGE_BASE_URL = r"/object_storage"
